# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(212228)
$foreground = rgb(E5E9EF)
$color0 = rgb(47484F)
$color1 = rgb(305340)
$color2 = rgb(5D5E64)
$color3 = rgb(756961)
$color4 = rgb(6F6F6E)
$color5 = rgb(A3856B)
$color6 = rgb(878F9C)
$color7 = rgb(D1D6DF)
$color8 = rgb(92969C)
$color9 = rgb(406E55)
$color10 = rgb(7C7D85)
$color11 = rgb(9C8C81)
$color12 = rgb(949592)
$color13 = rgb(D9B18F)
$color14 = rgb(B4BFD0)
$color15 = rgb(D1D6DF)
