# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(151516)
$foreground = rgb(D1E2FE)
$color0 = rgb(3C3C3E)
$color1 = rgb(965A7E)
$color2 = rgb(925E8A)
$color3 = rgb(397B7D)
$color4 = rgb(AA5F80)
$color5 = rgb(838259)
$color6 = rgb(5D81BE)
$color7 = rgb(B5CDF6)
$color8 = rgb(7F8FAC)
$color9 = rgb(C878A7)
$color10 = rgb(C37EB8)
$color11 = rgb(4CA4A6)
$color12 = rgb(E37EAB)
$color13 = rgb(AEAD76)
$color14 = rgb(7CABFD)
$color15 = rgb(B5CDF6)
