color0 #4b4453
color1 #ffb4ab
color2 #d7baff
color3 #d5bcf6
color4 #ffafd6
color5 #d7baff
color6 #d5bcf6
color7 #e8e0eb
color8 #968d9e
color9 #ffb4ab
color10 #d7baff
color11 #d5bcf6
color12 #ffafd6
color13 #d7baff
color14 #d5bcf6
color15 #e8e0eb

cursor                #e8e0eb
cursor_text_color     #15121a
background            #15121a
foreground            #e8e0eb
selection_foreground  #cdc3d5
selection_background  #4b4453
active_border_color   #d7baff
inactive_border_color #4b4453
url_color             #d7baff

active_tab_foreground   #440088
active_tab_background   #d7baff
inactive_tab_foreground #cdc3d5
inactive_tab_background #4b4453
cursor_trail_color      #cdc3d5
