color0 #4a4451
color1 #ffb4ab
color2 #d6baff
color3 #d1bfeb
color4 #ffafd8
color5 #d6baff
color6 #d1bfeb
color7 #e7e0e9
color8 #958e9c
color9 #ffb4ab
color10 #d6baff
color11 #d1bfeb
color12 #ffafd8
color13 #d6baff
color14 #d1bfeb
color15 #e7e0e9

cursor                #e7e0e9
cursor_text_color     #151218
background            #151218
foreground            #e7e0e9
selection_foreground  #ccc3d3
selection_background  #4a4451
active_border_color   #d6baff
inactive_border_color #4a4451
url_color             #d6baff

active_tab_foreground   #3f1678
active_tab_background   #d6baff
inactive_tab_foreground #ccc3d3
inactive_tab_background #4a4451
cursor_trail_color      #ccc3d3
