color0 #50443d
color1 #ffb4ab
color2 #efbc9d
color3 #dcc1b2
color4 #ccc998
color5 #efbc9d
color6 #dcc1b2
color7 #eae1dd
color8 #9d8e85
color9 #ffb4ab
color10 #efbc9d
color11 #dcc1b2
color12 #ccc998
color13 #efbc9d
color14 #dcc1b2
color15 #eae1dd

cursor                #eae1dd
cursor_text_color     #161310
background            #161310
foreground            #eae1dd
selection_foreground  #d4c3ba
selection_background  #50443d
active_border_color   #efbc9d
inactive_border_color #50443d
url_color             #efbc9d

active_tab_foreground   #482913
active_tab_background   #efbc9d
inactive_tab_foreground #d4c3ba
inactive_tab_background #50443d
cursor_trail_color      #d4c3ba
