# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #

# you can choose themes from $HOME/.config/kitty/kitty-themes/
include ./kitty-themes/01-Wallust.conf

font_family FantasqueSansM Nerd Font Mono
font_size 14.0
bold_font auto
italic_font auto
bold_italic_font auto

background_opacity 0.9
dynamic_background_opacity 1
confirm_os_window_close 0

# Animated cursor
cursor_trail 1

# change to x11 or wayland or leave auto
linux_display_server auto
allow_remote_control yes

scrollback_lines 2000
wheel_scroll_min_lines 1

enable_audio_bell no

window_padding_width 4

selection_foreground none
selection_background none

# 💡 將 Kitty 的複製貼上改為 Super+C / Super+V
map super+c copy_to_clipboard
map super+v paste_from_clipboard

# 💡 移除原本 Ctrl+Shift+C/V 的映射，避免按鍵習慣混淆
map ctrl+shift+c no_op
map ctrl+shift+v no_op

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5

tab_bar_edge bottom

tab_bar_style          powerline
tab_powerline_style    slanted
tab_title_template     "{index}: {title}"

# foreground/background/cursor are set by the active theme
