[backdrop]
enabled = false

[bar.default]
auto_hide = false
background_opacity = 0.5599999874830246
capsule = false
capsule_padding = 8.0
capsule_radius = "auto"
center = [ "active_window" ]
end = [
    "control-center",
    "weather",
    "tray",
    "notifications",
    "clipboard",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "battery",
    "temp",
    "session",
    "clock"
]
font_family = "FantasqueSansM Nerd Font"
font_weight = 700
layer = "top"
margin_edge = 0
margin_ends = 0
margin_opposite_edge = 0
padding = 10
panel_overlap = 0
position = "top"
radius = 0
radius_top_left = 10
radius_top_right = 10
shadow = false
start = [ "launcher", "wallpaper", "workspaces", "spacer_2", "taskbar" ]
thickness = 24
widget_spacing = 8

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[idle]
pre_action_fade_seconds = 3

[location]
auto_locate = true

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-2", "lockscreen-widget-0000000000000001", "lockscreen-widget-0000000000000002" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2"]
    box_height = 120.0
    box_width = 448.0
    cx = 960.0
    cy = 824.0
    output = "HDMI-A-2"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2".settings]
        background_color = "on_primary"
        background_opacity = 0.48999999999999999
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 224.0
    box_width = 304.0
    cx = 960.0
    cy = 536.0
    output = "HDMI-A-2"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        background_color = "surface"
        background_opacity = 0.68000000000000005
        background_padding = 10
        background_radius = 12
        center_text = false
        circle = true
        clock_style = "digital"
        color = "on_surface"
        font_family = ""
        format = "{:%H:%M}"
        shadow = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 112.0
    box_width = 224.0
    cx = 1792.0
    cy = 1096.0
    output = "HDMI-A-2"
    rotation = -0.0
    type = "weather"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background = false
        shadow = false

[nightlight]
enabled = false

[shell]
niri_overview_type_to_launch_enabled = true
settings_show_advanced = true
ui_scale = 1.1000000089406967

    [shell.panel]
    borders = true
    control_center_placement = "floating"
    launcher_position = "auto"
    open_near_click_control_center = true
    open_near_click_launcher = true
    open_near_click_wallpaper = true
    transparency_mode = "soft"
    wallpaper_placement = "floating"

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 3.0
    enabled = true
    shortcut = "5"
    variant = "destructive"

[theme]
builtin = "Noctalia"
community_palette = "Oxocarbon"
custom_palette = "purple-star-mc"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "kitty", "hyprland", "niri" ]
    enable_builtin_templates = true

        [theme.templates.user.sway-colors]
        input_path = "~/.config/noctalia/templates/sway-colors"
        output_path = "~/.config/sway/noctalia"
        post_hook = "swaymsg reload"

[wallpaper]
directory = "/home/mic/Pictures/wallpapers"

    [wallpaper.automation]
    enabled = true
    interval_seconds = 300

    [wallpaper.default]
    path = "/home/mic/Pictures/wallpapers/Dynamic-Wallpapers/Dark/Mountain_dark.png"

    [wallpaper.last]
    path = "/home/mic/Pictures/wallpapers/Dynamic-Wallpapers/Dark/Mountain_dark.png"

    [wallpaper.monitors.HDMI-A-2]
    path = "/home/mic/Pictures/wallpapers/Dynamic-Wallpapers/Dark/Mountain_dark.png"

[widget.active_window]
min_length = 132
scale = 1.0

[widget.network]
show_label = false

[widget.spacer_2]
type = "spacer"

[widget.taskbar]
capsule_padding = 9

[widget.weather]
show_condition = false

[widget.workspaces]
active_pill_size = 2.3000000000000003
display = "none"
inactive_pill_size = 1.3500000000000001
minimal = false
pill_scale = 0.70000000000000007