# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #D4D4D6
background         #16182A
cursor             #7D6595

active_tab_foreground     #16182A
active_tab_background     #D4D4D6
inactive_tab_foreground   #D4D4D6
inactive_tab_background   #16182A

active_border_color   #D4D4D6
inactive_border_color #16182A
bell_border_color     #5D81BE

color0      #A2A2A4
color1		#5D81BE
color2		#838259
color3		#AA5F80
color4		#397B7D
color5		#925E8A
color6		#965A7E
color7		#384D72
color8		#5778B1
color9		#7CABFD
color10		#AEAD76
color11		#E37EAB
color12		#4CA4A6
color13		#C37EB8
color14		#C878A7
color15		#B5CDF6
