# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #DFE0E5
background         #142140
cursor             #676971

active_tab_foreground     #142140
active_tab_background     #DFE0E5
inactive_tab_foreground   #DFE0E5
inactive_tab_background   #142140

active_border_color   #DFE0E5
inactive_border_color #142140
bell_border_color     #878F9C

color0      #B2B3BB
color1		#878F9C
color2		#A3856B
color3		#6F6F6E
color4		#756961
color5		#5D5E64
color6		#305340
color7		#51565E
color8		#7E8692
color9		#B4BFD0
color10		#D9B18F
color11		#949592
color12		#9C8C81
color13		#7C7D85
color14		#406E55
color15		#D1D6DF
