color0 #50453b
color1 #ffb4ab
color2 #f1bd86
color3 #dec2a7
color4 #c3cc8e
color5 #f1bd86
color6 #dec2a7
color7 #eae1da
color8 #9c8e82
color9 #ffb4ab
color10 #f1bd86
color11 #dec2a7
color12 #c3cc8e
color13 #f1bd86
color14 #dec2a7
color15 #eae1da

cursor                #eae1da
cursor_text_color     #17130f
background            #17130f
foreground            #eae1da
selection_foreground  #d4c4b6
selection_background  #50453b
active_border_color   #f1bd86
inactive_border_color #50453b
url_color             #f1bd86

active_tab_foreground   #492900
active_tab_background   #f1bd86
inactive_tab_foreground #d4c4b6
inactive_tab_background #50453b
cursor_trail_color      #d4c4b6
