color0 #434656
color1 #ffb4ab
color2 #b9c3ff
color3 #b9c3ff
color4 #f2afff
color5 #b9c3ff
color6 #b9c3ff
color7 #e2e1ef
color8 #8d8fa3
color9 #ffb4ab
color10 #b9c3ff
color11 #b9c3ff
color12 #f2afff
color13 #b9c3ff
color14 #b9c3ff
color15 #e2e1ef

cursor                #e2e1ef
cursor_text_color     #11131c
background            #11131c
foreground            #e2e1ef
selection_foreground  #c4c5da
selection_background  #434656
active_border_color   #b9c3ff
inactive_border_color #434656
url_color             #b9c3ff

active_tab_foreground   #002389
active_tab_background   #b9c3ff
inactive_tab_foreground #c4c5da
inactive_tab_background #434656
cursor_trail_color      #c4c5da
