color0 #454654
color1 #ffb4ab
color2 #bec2ff
color3 #bfc2fc
color4 #ffa9ff
color5 #bec2ff
color6 #bfc2fc
color7 #e3e1ec
color8 #908fa0
color9 #ffb4ab
color10 #bec2ff
color11 #bfc2fc
color12 #ffa9ff
color13 #bec2ff
color14 #bfc2fc
color15 #e3e1ec

cursor                #e3e1ec
cursor_text_color     #12131a
background            #12131a
foreground            #e3e1ec
selection_foreground  #c6c5d6
selection_background  #454654
active_border_color   #bec2ff
inactive_border_color #454654
url_color             #bec2ff

active_tab_foreground   #060ea3
active_tab_background   #bec2ff
inactive_tab_foreground #c6c5d6
inactive_tab_background #454654
cursor_trail_color      #c6c5d6
